### ISSUE TITLE
Token tailing equal mark (`=`) missing when passing by connection URL.

### ISSUE THREAD

**Issue by VergeDX** [wise-coders/influxdb-jdbc-driver#1]
If the token contains `=`, the `=` part will miss in HTTP(s) request.
It seems method `Connection connect(String, Properties)` parse HTTP query string by `=`.

**Comment by wise-coders** [comment]
I didn't understand what is wrong. The connect splits first by &, and then by =, only after the ? in the URL.
```
if ( ( idx = url.lastIndexOf("?") ) > -1 ){
                for ( String pair : url.substring( idx + 1 ).split("&")){
                    String[] keyVal = pair.split("=");
                    if ( keyVal.length == 2 ) {
```

**Comment by wise-coders** [comment]
Thank you for your reply. I got it now.
We added a fix and deployed a new version.
If you use the driver in DbSchema, please drop the folder .DbSchema from the user home directory. The latest driver will be downloaded.
